packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/shared/*'
  - 'tools/*'
  - 'libs/api-service/types'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - 'core-js-pure'
  - 'esbuild'
  - 'nx'
  - 'prisma'
